### ISSUE TITLE
Zpřehlednění kódu?

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/Chassis-rider-demo#1]
https://github.com/RoboticsBrno/Chassis-rider-demo/blob/f435646a96e6a8280404e797e6095c07dd80c4ee/Main_program/src/Motor.cpp#L29

Nebylo by lepší si místo `MotorLeft`, což je asi nějaká konstanta s ID motoru, uchovávat přímo referenci na levý motor?

```cpp
const int MotorLeftId = 1;
auto MotorLeft = rb::Manager::get().motor(MotorLeftId);

...

gPosL = MotorLeft.encoder()->value(); 
```

Lze to takhle používat? @Tasssadar 

PS: `auto` jsem použil jen proto, že se mi nechtělo hledat typ, ale možná by to zrovna zde dávalo smysl.

**Comment by Tasssadar** [comment]
Bude, ale ta reference musí být vytvořená až potom, co s zavolá Manager.install(), takže nemůže být globální. Musel by to být pointer, který se inicializuje někde v `setup()` :(
